#ifndef CONFIG_H
#define CONFIG_H

#define LEARNING_RATE 1.8
#define MIN_LEARNING_RATE 0.0001
#define LEARNING_RATE_DECAY 0.999

#define THETA 0.2
#define MAX_GRADIENT 10.0
#define MAX_LAYERS 128

#define ACTIVATION ACT_SIGMOID // ACT_{SIGMOID | RELU | TANH}
#define EPOCH_COUNT 20000

#define WEIGHT_INIT FULL // {XAVIER | FULL | NONE}
#define BIAS_INIT 0.0

#endif // CONFIG_H
